package com.sh.guessgame.mybatis.mapper;

import com.sh.guessgame.mybatis.model.BatchInfo;

public interface BatchInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int insert(BatchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int insertSelective(BatchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    BatchInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int updateByPrimaryKeySelective(BatchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int updateByPrimaryKey(BatchInfo record);
}