package com.sh.guessgame.mybatis.mapper;

import com.sh.guessgame.mybatis.model.TradeInfo;

public interface TradeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int insert(TradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int insertSelective(TradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    TradeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int updateByPrimaryKeySelective(TradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int updateByPrimaryKey(TradeInfo record);
}