package com.sh.guessgame.mybatis.mapper;

import com.sh.guessgame.mybatis.model.UserInfo;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);
    
    int deleteByUserId(String userId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    UserInfo selectByPrimaryKey(Long id);
    
    UserInfo selectByUserId(String userId);

    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int updateByPrimaryKey(UserInfo record);
}