package com.sh.guessgame.mybatis.mapper;

import com.sh.guessgame.mybatis.model.WinnerInfo;

public interface WinnerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table winner_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table winner_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int insert(WinnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table winner_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int insertSelective(WinnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table winner_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    WinnerInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table winner_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int updateByPrimaryKeySelective(WinnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table winner_info
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    int updateByPrimaryKey(WinnerInfo record);
}