package com.sh.guessgame.mybatis.model;

import java.util.Date;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.batch_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String batchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.choose_num
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String chooseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.price
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.num
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_amt
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String orderAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private Long userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_create
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.gmt_modify
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_no
     *
     * @return the value of order_info.order_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_no
     *
     * @param orderNo the value for order_info.order_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.batch_no
     *
     * @return the value of order_info.batch_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.batch_no
     *
     * @param batchNo the value for order_info.batch_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.choose_num
     *
     * @return the value of order_info.choose_num
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getChooseNum() {
        return chooseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.choose_num
     *
     * @param chooseNum the value for order_info.choose_num
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setChooseNum(String chooseNum) {
        this.chooseNum = chooseNum == null ? null : chooseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.price
     *
     * @return the value of order_info.price
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.price
     *
     * @param price the value for order_info.price
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.num
     *
     * @return the value of order_info.num
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.num
     *
     * @param num the value for order_info.num
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_amt
     *
     * @return the value of order_info.order_amt
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getOrderAmt() {
        return orderAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_amt
     *
     * @param orderAmt the value for order_info.order_amt
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setOrderAmt(String orderAmt) {
        this.orderAmt = orderAmt == null ? null : orderAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_no
     *
     * @return the value of order_info.user_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public Long getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_no
     *
     * @param userNo the value for order_info.user_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setUserNo(Long userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_create
     *
     * @return the value of order_info.gmt_create
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_create
     *
     * @param gmtCreate the value for order_info.gmt_create
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.gmt_modify
     *
     * @return the value of order_info.gmt_modify
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.gmt_modify
     *
     * @param gmtModify the value for order_info.gmt_modify
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}