package com.sh.guessgame.mybatis.model;

import java.util.Date;

public class TradeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.id
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.trade_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.winner_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String winnerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.user_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private Long userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.amt
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String amt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.status
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.order_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.gmt_create
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.gmt_modify
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.id
     *
     * @return the value of trade_info.id
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.id
     *
     * @param id the value for trade_info.id
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.trade_no
     *
     * @return the value of trade_info.trade_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.trade_no
     *
     * @param tradeNo the value for trade_info.trade_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.winner_no
     *
     * @return the value of trade_info.winner_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getWinnerNo() {
        return winnerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.winner_no
     *
     * @param winnerNo the value for trade_info.winner_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setWinnerNo(String winnerNo) {
        this.winnerNo = winnerNo == null ? null : winnerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.user_no
     *
     * @return the value of trade_info.user_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public Long getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.user_no
     *
     * @param userNo the value for trade_info.user_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setUserNo(Long userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.amt
     *
     * @return the value of trade_info.amt
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.amt
     *
     * @param amt the value for trade_info.amt
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setAmt(String amt) {
        this.amt = amt == null ? null : amt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.status
     *
     * @return the value of trade_info.status
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.status
     *
     * @param status the value for trade_info.status
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.order_no
     *
     * @return the value of trade_info.order_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.order_no
     *
     * @param orderNo the value for trade_info.order_no
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.gmt_create
     *
     * @return the value of trade_info.gmt_create
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.gmt_create
     *
     * @param gmtCreate the value for trade_info.gmt_create
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.gmt_modify
     *
     * @return the value of trade_info.gmt_modify
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.gmt_modify
     *
     * @param gmtModify the value for trade_info.gmt_modify
     *
     * @mbg.generated Tue Oct 09 15:43:49 CST 2018
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}